apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: f9au5i8pt-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-3177828a8b.s0qp.p3.openshiftapps.com/rhtap/rhtap-qe:e47d48be40240f12f9507ccf516df899c75eb16c@sha256:6937489837b8b1a31d8aa728e1ca842ddd73da694e91fb9a1e175571427772a9
          name: container-image
